#login xpath
usernamexpath="xpath=//input[contains(@formcontrolname,'username')] "
passwordxpath="xpath=//input[contains(@formcontrolname,'password')]"
continuebutton="xpath=//button[contains(@class,'btn btn-primary')] "
#ADD operator
operatorsbutton="xpath=//span[text()='Operators'] "
addoperators="xpath=//button[contains(@routerlink,'user')]"
firstnameop="xpath=//input[@formcontrolname='firstname'] "
lastnameop="xpath=//input[@formcontrolname='lastname'] "
usernameop="xpath=//input[contains(@formcontrolname,'username')]"
passwordop=" xpath=//input[contains(@formcontrolname,'password')]"
repeatpassop="xpath=//input[contains(@formcontrolname,'repeat_Password')]"
carparkFeaturesop=" xpath= //span[contains(@class, 'tab-title-cls') and contains(text(), 'Carpark & Features')]"
carparkop="xpath=//select[contains(@formcontrolname , 'carPark')]"
grantedfeaturesop=" xpath=//ng-select[contains(@class, 'ng-select') and contains(@class, 'ng-select-multiple') and contains(@class, 'ng-select-searchable') and contains(@class, 'ng-select-clearable')]"
ticketinformation=" xpath=//div[contains(@class, 'ng-option') and .//span[contains(@class, 'ng-option-label') and text()='Ticket Information']]"
payment="xpath=//div[contains(@class, 'ng-option') and .//span[contains(text(), 'Payment')]]"
validation="xpath=//div[contains(@class, 'ng-option') and .//span[contains(text(), 'Validation')]]"
production="xpath=//div[contains(@class, 'ng-option') and .//span[contains(text(), 'Production')]]"
devicecontrol1="xpath=//div[contains(@class, 'ng-option') and .//span[contains(text(), 'Device Control')]]"
PaymentShift="xpath=//span[contains(@class, 'tab-title-cls') and contains(text(), 'Payment & Shift')]" 
contractop=" xpath=//input[@formcontrolname='cashierContractId']   "
consumer1="xpath=//input[@formcontrolname='cashierConsumerId'] "
cashierpasswrd="xpath=//input[@formcontrolname='cashierPassword']"
paymentmeth="xpath=//select[contains(@formcontrolname , 'paymentMethod')]"
validprod=" xpath=//span[contains(@class, 'tab-title-cls') and contains(text(), 'Validation & Production')]"
Validationarticles="(//div[contains(@class, 'ng-input') and @role='combobox'])[2]"
HourDiscount="xpath=//span[contains(@class, 'ng-option-label') and contains(text(), '1 Hour Discount')]"
EURDiscount="xpath=//div[contains(@class, 'ng-option') and .//span[contains(text(), '5 EUR Discount')]]"
freepark=" xpath=//div[contains(@class, 'ng-option') and .//span[contains(text(), 'Free Parking')]]"
productionarticles="(//div[contains(@class, 'ng-input') and @role='combobox'])[3]"
lostticket=" xpath=//div[contains(@class, 'ng-option') and .//span[contains(text(), 'Lost Parking Ticket')]]"
prepaid=" xpath=//div[contains(@class, 'ng-option') and .//span[contains(text(), 'Prepaid 1 Day')]]"
devicecontrol="xpath=//span[contains(text(), 'DEVICE CONTROL')]"
#checkbox1=" xpath= //input[@type='checkbox' and @formcontrolname='canOpenBarrierForPassage' and contains(@class, 'form-check-input')] "
#checkbox2=" xpath= //input[@type='checkbox' and @formcontrolname='canOpenForDoorReader' and contains(@class, 'form-check-input')] "
#ENTRY
checkbox1="//input[contains(@formcontrolname, 'canOpenBarrierForEntry')]"
checkbox2="//input[contains(@formcontrolname, 'canCloseBarrierForEntry')]"
checkbox3="//input[contains(@formcontrolname, 'canLockBarrierForEntry')]"
checkbox4="//input[contains(@formcontrolname, 'canUnlockBarrierForEntry')]"
checkbox5="//input[contains(@formcontrolname, 'canSetOffOperationForEnt y')]"
checkbox6="//input[contains(@formcontrolname, 'canSetInOperationForEntry')]"
#EXIT'
checkbox7="//input[contains(@formcontrolname, 'canOpenBarrierForExit')]"
checkbox8="//input[contains(@formcontrolname, 'canCloseBarrierForExit')]"
checkbox9="//input[contains(@formcontrolname, 'canLockBarrierForExit')]"
checkbox10="//input[contains(@formcontrolname, 'canUnlockBarrierForExit')]"
checkbox11="//input[contains(@formcontrolname, 'canSetOffOperationForExit')]"
checkbox12="//input[contains(@formcontrolname, 'canSetInOperationForExit')]"
checkbox13="//input[contains(@formcontrolname, 'canEnableJamForExit')]"
checkbox14="//input[contains(@formcontrolname, 'canDisableJamForExit')]"
#Passage
checkbox15="//input[contains(@formcontrolname, 'canOpenBarrierForPassage')]"
checkbox6="//input[contains(@formcontrolname, 'canCloseBarrierForPassage')]"
checkbox17="//input[contains(@formcontrolname, 'canSetOffOperationForPassage')]"
checkbox18="//input[contains(@formcontrolname, 'canSetInOperationForPassage')]"

#DOOR READER
checkbox19="//input[contains(@formcontrolname, 'canOpenForDoorReader')]"
checkbox20="//input[contains(@formcontrolname, 'canCloseForDoorReader')]"
checkbox21="//input[contains(@formcontrolname, 'canLockBarrierForDoorReader')]"
checkbox22="//input[contains(@formcontrolname, 'canUnlockBarrierForDoorReader')]"
checkbox23="//input[contains(@formcontrolname, 'canSetOffOperationDoorForDoorReader')]"
checkbox24="//input[contains(@formcontrolname, 'canSetInOperationForDoorReader')]"
#AUTOMATIC PAY STATION 
checkbox25="//input[contains(@formcontrolname, 'canReplaceTicketForAutomaticPayStation')]"
checkbox26="//input[contains(@formcontrolname, 'canSetOffOperationForAutomaticPayStation')]"
checkbox27="//input[contains(@formcontrolname, 'canSetInOperationForAutomaticPayStation')]"
#save
saveop="xpath=//button[contains(@class, 'btn btn-primary')]"
buttonop = "//button[text()='Ok, got it!']"

#ADD carparks 
carparksbut="xpath=//span[text()='Carparks']"
ADDcarpaksbutt='xpath=//*[@id="kt_app_content_container"]/app-carparks-listing/div[2]/div[1]/div[2]/div/button'
carpakname="xpath=//input[contains(@formcontrolname , 'carparkName')]"
operatorid="xpath=//input[contains(@formcontrolname , 'operatorId')]"
ZRid="xpath=//input[contains(@formcontrolname , 'zrId')] "
protocol="xpath=//select[contains(@formcontrolname , 'protocol')]  "
ipadresscrap="xpath=//input[contains(@formcontrolname , 'ipAdress')] "
portcarp="xpath=//input[contains(@formcontrolname , 'port')] "
cashiercontract="xpath=//input[contains(@formcontrolname , 'cashierContractId')] "
casierconsumer=" xpath=//input[contains(@formcontrolname , 'cashierConsumerId')]"
passwordcarpark="xpath=//input[contains(@formcontrolname , 'cashierPassword')] "
lpr="xpath=//select[contains(@formcontrolname , 'lpr')]"
lfk=" xpath=//select[contains(@formcontrolname , 'lfk')] "
curency="xpath=//ng-select[contains(@formcontrolname , 'currency')]  "
#add validation 
articlvalid="//span[text()='Validation Articles']"
add_validation="//button[contains(@routerlink,'validation')]"
namevalid="//input[contains(@formcontrolname,'name')]"
typevalid="//select[contains(@formcontrolname,'type')]"
valuevalid="//input[contains(@formcontrolname,'value')]"
carparksvalid="//div[contains(@class,'ng-value')]"
pumccarpark="//div[contains(@class, 'ng-option') and .//span[contains(text(), 'PUMC Carpark')]]"
Qpark="//div[contains(@class, 'ng-option') and .//span[contains(text(), 'Qpark')]]"
savevalid="//button[contains(@id, 'kt_modal_update_customer_submit')]"
savevalidddd="//button[contains(@class, 'swal2-confirm') and contains(text(), 'Ok, got it!')]"
#add production
articalproduc="//span[text()='Production Articles']"
add_productio="//button[contains(@routerlink,'production')]"
nameproduction="//input[contains(@formcontrolname,'name')]"
typeproduc="//select[contains(@formcontrolname,'productType')]"
priceproduc="//input[contains(@formcontrolname,'price')]"
prodcarparks="//ng-select[contains(@formcontrolname,'carParks')]"
toprod="//ng-select[contains(@formcontrolname,'to')]"
Selectnextday="//span[text()='Start of next day'][1]"
nextmoth="//span[text()='End of the next month']"
fromprod="//div[contains(@class,'ng-select-container')]"   
saveproduc="//button[contains(@id, 'kt_modal_update_customer_submit')]"

